import React from 'react';
import {
  Paper,
  Typography,
  List,
  ListItem,
  ListItemText,
  ListItemSecondaryAction,
  IconButton,
  Button,
  Box,
  Select,
  MenuItem,
} from '@mui/material';
import { Delete, Download, Edit } from '@mui/icons-material';
import CodeIcon from '@mui/icons-material/Code';
import SaveIcon from '@mui/icons-material/Save';
import FormatListBulletedIcon from '@mui/icons-material/FormatListBulleted';
import Tooltip from '@mui/material/Tooltip';
import DeleteIcon from '@mui/icons-material/Delete';
import DownloadIcon from '@mui/icons-material/Download';
import FileDownloadIcon from '@mui/icons-material/FileDownload';
import FolderZipIcon from '@mui/icons-material/FolderZip';
import { useLanguage } from '../contexts/LanguageContext';

function MacroList({ hotkeys, onDeleteHotkey, onDownload }) {
  const { currentLanguage, setCurrentLanguage, t } = useLanguage();

  const getActionDescription = (action) => {
    switch (action.type) {
      case 'openApp':
        return `${t('actions.openApp')}: ${action.path}`;
      case 'openWebsite':
        return `${t('actions.openWebsite')}: ${action.path}`;
      case 'sendKeys':
        return `${t('actions.sendKeys')}: ${action.path}`;
      case 'replaceText':
        return `${t('actions.replaceText')}: ${action.path} → ${action.replacement}`;
      case 'volumeUp':
        return t('actions.volumeUp');
      case 'volumeDown':
        return t('actions.volumeDown');
      case 'brightnessUp':
        return t('actions.brightnessUp');
      case 'brightnessDown':
        return t('actions.brightnessDown');
      case 'quickNote':
        return t('actions.quickNote');
      case 'startTimer':
        return t('actions.startTimer');
      case 'clipboardHistory':
        return t('actions.clipboardHistory');
      case 'aiMenu':
        return t('actions.aiMenu');
      default:
        return t('actions.unknown');
    }
  };

  const handleDownload = (hotkey) => {
    const script = generateAHKScript([hotkey]);
    const blob = new Blob([script], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${hotkey.name}.ahk`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadAll = () => {
    if (hotkeys.length === 0) return;
    
    const script = generateAHKScript(hotkeys);
    const blob = new Blob([script], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'all_macros.ahk';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadSeparateFiles = () => {
    if (hotkeys.length === 0) return;
    
    hotkeys.forEach(hotkey => {
      const script = generateAHKScript([hotkey]);
      const blob = new Blob([script], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${hotkey.name}.ahk`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    });
  };

  const stripKeyCode = (key) => {
    return key.split(' (')[0];
  };

  const extractOriginalKey = (displayKey) => {
    // Extract the original key from the format "A (KeyA)"
    const match = displayKey.match(/^([^ ]+)/);
    return match ? match[1] : displayKey;
  };

  const convertToAHKKey = (key) => {
    // Handle modifiers
    switch (key.toUpperCase()) {
      case 'CTRL':
        return '^';
      case 'ALT':
        return '!';
      case 'SHIFT':
        return '+';
      case 'WIN':
        return '#';
      // Handle special keys
      case 'ENTER':
        return '{Enter}';
      case 'ESCAPE':
      case 'ESC':
        return '{Escape}';
      case 'TAB':
        return '{Tab}';
      case 'SPACE':
        return '{Space}';
      case 'BACKSPACE':
        return '{Backspace}';
      case 'DELETE':
        return '{Delete}';
      case 'UP':
        return '{Up}';
      case 'DOWN':
        return '{Down}';
      case 'LEFT':
        return '{Left}';
      case 'RIGHT':
        return '{Right}';
      case 'PAGEUP':
        return '{PgUp}';
      case 'PAGEDOWN':
        return '{PgDn}';
      case 'HOME':
        return '{Home}';
      case 'END':
        return '{End}';
      case 'INSERT':
        return '{Insert}';
      case 'F1': case 'F2': case 'F3': case 'F4': case 'F5': case 'F6':
      case 'F7': case 'F8': case 'F9': case 'F10': case 'F11': case 'F12':
        return `{${key}}`;
      default:
        return key;
    }
  };

  const generateAHKScript = (selectedHotkeys) => {
    const header = `; AutoHotkey Script Generated by AHK Generator
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

; === Macro Configuration ===
; This script contains your custom macros and text replacements

; Initialize custom AI menu
Menu, AI_Menu, Add, Open ChatGPT, OpenChatGPT
Menu, AI_Menu, Add, Ask GPT (Prompt), PromptGPT
return  ; End of auto-execute section

; Function for clipboard history
ClipboardHistory() {
    FormatTime, TimeString,, yyyy-MM-dd HH:mm:ss
    FileAppend, %TimeString%: %Clipboard%\\n, %A_ScriptDir%/clipboard_history.txt
    TrayTip, Clipboard History, Entry saved!, 2
    return
}

; Function for quick notes
QuickNote() {
    global NoteContent  ; Make GUI control variable global
    Gui, Note:New
    Gui, Note:Add, Edit, vNoteContent w300 h200
    Gui, Note:Add, Button, gSaveNote, Save Note
    Gui, Note:Show,, Quick Note
    return

SaveNote:
    Gui, Note:Submit
    FormatTime, TimeString,, yyyy-MM-dd HH:mm:ss
    FileAppend, %TimeString%:\`n%NoteContent%\`n---\`n, %A_ScriptDir%/quick_notes.txt
    return
}

; Function for timer
StartTimer() {
    InputBox, Minutes, Timer, Enter minutes:
    if !ErrorLevel {
        SetTimer, TimerDone, % Minutes * 60000
        TrayTip, Timer Started, Will notify in %Minutes% minutes, 2
    }
    return

TimerDone:
    SetTimer, TimerDone, Off
    MsgBox Timer Done!
    return
}

; AI Menu Labels
OpenChatGPT:
    Run, https://chat.openai.com
    return

PromptGPT:
    InputBox, userPrompt, Ask ChatGPT, Enter your question:
    if (userPrompt != "") {
        query := StrReplace(userPrompt, " ", "+")
        Run, https://chat.openai.com/?q=%query%
    }
    return

HandleExit:
    ExitApp
    return

; === Start of Hotkey Definitions ===`;

    const hotkeyScripts = selectedHotkeys.map(hotkey => {
      if (hotkey.action.type === 'replaceText') {
        return `; ${hotkey.name}
:*:${hotkey.action.path}::${hotkey.action.replacement}

`;
      }

      const keys = hotkey.keys.map(k => convertToAHKKey(extractOriginalKey(k))).join('');
      let action = '';
      
      switch (hotkey.action.type) {
        case 'openApp':
          action = `Run, ${hotkey.action.path}`;
          break;
        case 'openWebsite':
          action = `Run, ${hotkey.action.path}`;
          break;
        case 'sendKeys':
          action = `SendInput, ${hotkey.action.path}`;
          break;
        case 'volumeUp':
          action = 'Send, {Volume_Up}';
          break;
        case 'volumeDown':
          action = 'Send, {Volume_Down}';
          break;
        case 'brightnessUp':
          action = 'Run, nircmd.exe changesysvolume 2000';
          break;
        case 'brightnessDown':
          action = 'Run, nircmd.exe changesysvolume -2000';
          break;
        case 'quickNote':
          action = 'QuickNote()';
          break;
        case 'startTimer':
          action = 'StartTimer()';
          break;
        case 'clipboardHistory':
          action = 'ClipboardHistory()';
          break;
        case 'aiMenu':
          action = 'Menu, AI_Menu, Show  ; Show the AI Assistant menu';
          break;
        default:
          action = `; Unknown action type: ${hotkey.action.type}`;
          break;
      }

      return `; ${hotkey.name}
${keys}::
${action}
return  ; End of ${hotkey.name} hotkey

`;
    }).join('\n');

    return header + hotkeyScripts;
  };

  return (
    <Paper 
      elevation={3} 
      sx={{ 
        p: 3,
        borderRadius: 2,
        background: 'linear-gradient(145deg, #ffffff 0%, #f5f5f5 100%)',
        boxShadow: '0 4px 20px rgba(0,0,0,0.1)'
      }}
    >
      <Box sx={{ display: 'flex', alignItems: 'center', mb: 3 }}>
        <FormatListBulletedIcon sx={{ mr: 1, color: 'primary.main' }} />
        <Typography variant="h6" component="h2" sx={{ flexGrow: 1 }}>
          {t('yourMacros')}
        </Typography>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
          <Tooltip title={t('downloadAllInOne')}>
            <IconButton 
              onClick={handleDownloadAll}
              color="primary"
              sx={{ mr: 1 }}
            >
              <FileDownloadIcon />
            </IconButton>
          </Tooltip>
          <Tooltip title={t('downloadSeparate')}>
            <IconButton 
              onClick={handleDownloadSeparateFiles}
              color="primary"
            >
              <FolderZipIcon />
            </IconButton>
          </Tooltip>
        </Box>
      </Box>

      {hotkeys.length === 0 ? (
        <Paper 
          sx={{ 
            p: 3, 
            textAlign: 'center',
            bgcolor: 'grey.50',
            borderRadius: 2,
            border: '1px dashed',
            borderColor: 'grey.300'
          }}
        >
          <Typography color="textSecondary">
            {t('noMacrosYet')}
          </Typography>
        </Paper>
      ) : (
        <List sx={{ 
          bgcolor: 'background.paper',
          borderRadius: 2,
          border: '1px solid',
          borderColor: 'divider'
        }}>
          {hotkeys.map((hotkey, index) => (
            <ListItem
              key={index}
              secondaryAction={
                <Box sx={{ display: 'flex' }}>
                  <Tooltip title={t('downloadMacro')}>
                    <IconButton 
                      edge="end" 
                      aria-label="download"
                      onClick={() => handleDownload(hotkey)}
                      sx={{ 
                        mr: 1,
                        color: 'primary.main',
                        '&:hover': {
                          bgcolor: 'primary.lighter'
                        }
                      }}
                    >
                      <DownloadIcon />
                    </IconButton>
                  </Tooltip>
                  <Tooltip title={t('deleteMacro')}>
                    <IconButton 
                      edge="end" 
                      aria-label="delete"
                      onClick={() => onDeleteHotkey(index)}
                      sx={{ 
                        color: 'error.main',
                        '&:hover': {
                          bgcolor: 'error.lighter'
                        }
                      }}
                    >
                      <DeleteIcon />
                    </IconButton>
                  </Tooltip>
                </Box>
              }
              sx={{
                borderBottom: index < hotkeys.length - 1 ? '1px solid' : 'none',
                borderColor: 'divider',
                '&:hover': {
                  bgcolor: 'action.hover'
                }
              }}
            >
              <ListItemText
                primary={
                  <Typography variant="subtitle1" component="div">
                    {hotkey.name}
                  </Typography>
                }
                secondary={
                  <Box>
                    <Typography 
                      variant="body2" 
                      color="primary"
                      component="span"
                      sx={{ 
                        display: 'inline-block',
                        bgcolor: 'primary.lighter',
                        px: 1,
                        py: 0.5,
                        borderRadius: 1,
                        mr: 1
                      }}
                    >
                      {hotkey.keys.join(' + ')}
                    </Typography>
                    <Typography 
                      variant="body2" 
                      color="textSecondary"
                      component="span"
                    >
                      {getActionDescription(hotkey.action)}
                    </Typography>
                  </Box>
                }
              />
            </ListItem>
          ))}
        </List>
      )}
    </Paper>
  );
}

export default MacroList; 